-- 국가별, 도시별 매출액
-- 국가별, 도시별 매출액을 구하기 위해서 ERD를 살펴보면 해당 주문 건이 발생한 국가, 도시를 파악하기 위해서 CUSTOMERS 테이블의 COUNTRY를 이용해야 합닏나.
-- 즉 ORDERS, CUSTOMERS, ORDERDETAILS를 모두 사용해야 합니다.
-- 먼저 ORDERS, ORDERDETAILS, CUSTOMERS 3가지 테이블을 결합해야 합니다. 각 테이블을 연결하는 필드는 ORDERNUMBER, CUSTOMERNUMBER 입니다.
SELECT *
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
LEFT JOIN CLASSICMODELS.CUSTOMERS C
ON A.CUSTOMERNUMBER = C.CUSTOMERNUMBER;

-- 필요한 컬럼(COUNTRY, CITY, 매출액(PRICEEACH*QUANTITYORDERED)을 호출합니다
SELECT C.COUNTRY, C.CITY, B.PRICEEACH*B.QUANTITYORDERED
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
LEFT JOIN CLASSICMODELS.CUSTOMERS C
ON A.CUSTOMERNUMBER = C.CUSTOMERNUMBER;

-- CUSTOMERS 테이블에서 국가(COUNTRY), 도시(CITY)를 불러오고, 2가지 칼럼으로 그룹핑을 진행합니다. 
-- 이후 ORDERDETAILS 테이블의 PRICEEACH*QUANTITYORDERED를 합해 국가별, 도시별 매출액을 구합니다.
SELECT C.COUNTRY, C.CITY, SUM(B.PRICEEACH*B.QUANTITYORDERED)
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
LEFT JOIN CLASSICMODELS.CUSTOMERS C
ON A.CUSTOMERNUMBER = C.CUSTOMERNUMBER
GROUP BY 1, 2
ORDER BY 1, 2;