-- 재구매율
-- 연도별로 재구매율을 계산합니다. 재구매율은 특정 기간 1 구매자 중 특정 기간 2에 연달아 구매한 구매자의 비중을 의미합니다.
-- ORDERS 테이블을 결합하는데 CUSTOMERNUMBER와 ORDERDATE의 데이터를 결합하게 됩니다. 
-- 이때 ORDER(A)의 SUBSTR(A ..)와 B의 SUBSTR(B ..) - 1을 결합하게 되어 A를 기준으로 1년 단위의 구매율을 비교합니다.
-- 예를 들어, 2003년도 거래 건에는 2004년도 거래가 매칭되지만 2004년도 거래 건에는 2005년 거래가 없어서 어떤 값도 매칭되지 않습니다.
-- A의 주문 연도로 그룹핑한 후 A와 B의 CUSTOMERNUMBER를 기준으로 COUNT하면 구매자 수를 알수있고, 두 값을 나누면 최종적으로 각 연도의 Retention rate를 구할 수 있습니다.
SELECT SUBSTR(A.ORDERDATE, 1, 4) YY,
COUNT(DISTINCT A.CUSTOMERNUMBER) CLI_1,
COUNT(DISTINCT B.CUSTOMERNUMBER) CLI_2,
COUNT(DISTINCT B.CUSTOMERNUMBER)/COUNT(DISTINCT A.CUSTOMERNUMBER) RETENTION_RATE
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER AND SUBSTR(A.ORDERDATE, 1, 4) = SUBSTR(B.ORDERDATE, 1, 4) - 1
GROUP BY 1;

-- 국가별 재구매율
-- 쿼리를 작성하기 전에 데이터를 어떻게 구조화해야 할지 생각합니다.
-- A 국가 거주 구매자 중 다음 연도에도 구매를 한 구매자의 비중으로 구할 수 있습니다. 
-- 앞에서 작성한 쿼리에 고객의 거주 국가 정보를 결합한 후 거주 국가로 그룹핑해 재구매율을 구하면 됩니다.
SELECT C.COUNTRY,
SUBSTR(A.ORDERDATE, 1, 4) YY,
COUNT(DISTINCT A.CUSTOMERNUMBER) CLI_1,
COUNT(DISTINCT B.CUSTOMERNUMBER) CLI_2,
COUNT(DISTINCT B.CUSTOMERNUMBER)/COUNT(DISTINCT A.CUSTOMERNUMBER) RETENTION_RATE
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER AND SUBSTR(A.ORDERDATE, 1, 4) = SUBSTR(B.ORDERDATE, 1, 4) - 1
LEFT JOIN CLASSICMODELS.CUSTOMERS C
ON A.CUSTOMERNUMBER = C.CUSTOMERNUMBER
GROUP BY 1, 2;