-- 인당 매출액(연도별)
-- 기간별로 평균 인당 고객 매출액을 비교하면, 고객 1명이 우리의 서비스에 얼마를 지불하는지 그 변화를 파악할 수 있습니다.
-- 연도별 매출액에서 구매자 수로 나누면 연도별 인당 매출액을 알 수 있습니다.
SELECT SUBSTR(A.ORDERDATE,1,4) YY,
COUNT(DISTINCT A.CUSTOMERNUMBER) N_PURCHASE,
SUM(B.PRICEEACH * B.QUANTITYORDERED) SALES,
SUM(B.PRICEEACH * B.QUANTITYORDERED)/ COUNT(DISTINCT A.CUSTOMERNUMBER) AMV
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
GROUP BY 1
ORDER BY 1;

-- 건당 구매 금액(ATV, Average Transaction Value)(연도별)
-- ATV : 1건의 거래는 평균적으로 얼마의 매출을 발생시키는 가
-- 매출을 구매자 수가 아닌 구매 건수로 나누면 건당 구매 금액을 쉽게 구할 수 있습니다.
SELECT SUBSTR(A.ORDERDATE,1,4) YY,
COUNT(DISTINCT A.ORDERNUMBER) N_PURCHASE,
SUM(B.PRICEEACH * B.QUANTITYORDERED) SALES,
SUM(B.PRICEEACH * B.QUANTITYORDERED) / COUNT(DISTINCT A.ORDERNUMBER) ATV
FROM CLASSICMODELS.ORDERS A
LEFT JOIN CLASSICMODELS.ORDERDETAILS B
ON A.ORDERNUMBER = B.ORDERNUMBER
GROUP BY 1
ORDER BY 1;